<div class="mb-3">
    <div class="row">
        <div class="col-lg-6">
            <h2><?php echo $page_title; ?></h2>
        </div>
        <div class="col-lg-6 text-end">
			<a href="<?php echo site_url('admin/variable/add'); ?>" class="btn btn-secondary">
				<span class="fa fa-plus"></span> New Variable
			</a>
        </div>
    </div>
</div>

<?php echo $this->session->flashdata('message');?>

<div class="card">
	<div class="card-body">
		
<?php 
	// This is view for autogenerated table
	// If you want custom appearance, you can make your own view
	$this->load->view('admin/_datatable', compact('fields','results','pagination'));
?>

	</div>
</div>